name: Build and Deploy to AWS Lightsail

on:
  push:
    branches:
      - main # Adjust to the branch you want to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1" # Adjust to the Go version you need

      # Step 3: Build the project
      - name: Build Go project
        run: go build -o myapp ./cmd/main.go # Replace 'main.go' with your actual entry point

      # Step 4: List files after build
      - name: List files after build
        run: ls -la

      # Step 5: Add SSH key for deployment
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.LIGHTSAIL_IP }}

      # Step 6: Create temporary directory on Lightsail
      - name: Create temporary directory
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
            sudo mkdir -p /home/ubuntu/myapp_tmp
            sudo chown -R $USER:$USER /home/ubuntu/myapp_tmp
          EOF

      # Step 7: Copy binary to Lightsail
      - name: Copy binary to Lightsail
        run: |
          scp -o StrictHostKeyChecking=no ./myapp ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_IP }}:/home/ubuntu/myapp_tmp/myapp

      # Step 8: Deploy and restart service
      - name: Deploy and restart service
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
            set -e  # Exit on error
            sudo systemctl stop myapp.service || true  # Stop the application service, ignore if it fails
            sudo rm -rf /home/ubuntu/myapp  # Remove the old application
            sudo mv /home/ubuntu/myapp_tmp/myapp /home/ubuntu/myapp  # Move the new binary to the target directory
            sudo systemctl start myapp.service  # Start the application service
          EOF
